package v2

import "time"

// =======================
// Market & Token Data  5 api
// ========================

// ========================
// Token Security API Types
// ========================

type TokenSecurityRequest struct {
	Address    string `json:"address"`              // Token contract address (required)
	Blockchain string `json:"blockchain,omitempty"` // Blockchain name (optional)
}
type TokenSecurityResponse struct {
	Data struct {
		Address                      string      `json:"address"`
		ChainID                      string      `json:"chainId"`
		ContractHoldingsPercentage   float64     `json:"contractHoldingsPercentage"`
		ContractBalanceRaw           string      `json:"contractBalanceRaw"`
		BurnedHoldingsPercentage     float64     `json:"burnedHoldingsPercentage"`
		TotalBurnedBalanceRaw        string      `json:"totalBurnedBalanceRaw"`
		BuyFeePercentage             int         `json:"buyFeePercentage"`
		SellFeePercentage            int         `json:"sellFeePercentage"`
		MaxWalletAmountRaw           interface{} `json:"maxWalletAmountRaw"`
		MaxSellAmountRaw             interface{} `json:"maxSellAmountRaw"`
		MaxBuyAmountRaw              interface{} `json:"maxBuyAmountRaw"`
		MaxTransferAmountRaw         interface{} `json:"maxTransferAmountRaw"`
		IsLaunchpadToken             bool        `json:"isLaunchpadToken"`
		Top10HoldingsPercentage      float64     `json:"top10HoldingsPercentage"`
		Top50HoldingsPercentage      float64     `json:"top50HoldingsPercentage"`
		Top100HoldingsPercentage     float64     `json:"top100HoldingsPercentage"`
		Top200HoldingsPercentage     float64     `json:"top200HoldingsPercentage"`
		IsMintable                   bool        `json:"isMintable"`
		IsFreezable                  interface{} `json:"isFreezable"`
		ProTraderVolume24HPercentage float64     `json:"proTraderVolume24hPercentage"`
	} `json:"data"`
}

// ========================
// Token Details API Types
// ========================

type TokenDetailsRequest struct {
	Address    string `json:"address"`              // Token contract address (required)
	Blockchain string `json:"blockchain,omitempty"` // Blockchain name (optional)
}
type TokenDetailsResponse struct {
	Data struct {
		Address                    string  `json:"address"`
		ChainID                    string  `json:"chainId"`
		Symbol                     string  `json:"symbol"`
		Name                       string  `json:"name"`
		Decimals                   int     `json:"decimals"`
		ID                         any     `json:"id"`
		PriceUSD                   float64 `json:"priceUSD"`
		PriceToken                 float64 `json:"priceToken"`
		PriceTokenString           string  `json:"priceTokenString"`
		ApproximateReserveUSD      float64 `json:"approximateReserveUSD"`
		ApproximateReserveTokenRaw string  `json:"approximateReserveTokenRaw"`
		ApproximateReserveToken    float64 `json:"approximateReserveToken"`
		TotalSupply                float64 `json:"totalSupply"`
		CirculatingSupply          float64 `json:"circulatingSupply"`
		MarketCapUSD               float64 `json:"marketCapUSD"`
		MarketCapDilutedUSD        float64 `json:"marketCapDilutedUSD"`
		Logo                       any     `json:"logo"`
		Rank                       any     `json:"rank"`
		Cexs                       []any   `json:"cexs"`
		Exchange                   struct {
			Name string `json:"name"`
			Logo string `json:"logo"`
		} `json:"exchange"`
		Source                    any     `json:"source"`
		LiquidityUSD              float64 `json:"liquidityUSD"`
		LiquidityMaxUSD           float64 `json:"liquidityMaxUSD"`
		Bonded                    bool    `json:"bonded"`
		BondingPercentage         float64 `json:"bondingPercentage"`
		Type                      string  `json:"type"`
		TokenType                 any     `json:"tokenType"`
		Deployer                  any     `json:"deployer"`
		BondedAt                  any     `json:"bondedAt"`
		PriceChange1MinPercentage float64 `json:"priceChange1minPercentage"`
		PriceChange5MinPercentage float64 `json:"priceChange5minPercentage"`
		PriceChange1HPercentage   float64 `json:"priceChange1hPercentage"`
		PriceChange4HPercentage   float64 `json:"priceChange4hPercentage"`
		PriceChange6HPercentage   float64 `json:"priceChange6hPercentage"`
		PriceChange12HPercentage  float64 `json:"priceChange12hPercentage"`
		PriceChange24HPercentage  float64 `json:"priceChange24hPercentage"`
		Volume1MinUSD             float64 `json:"volume1minUSD"`
		Volume5MinUSD             float64 `json:"volume5minUSD"`
		Volume15MinUSD            float64 `json:"volume15minUSD"`
		Volume1HUSD               float64 `json:"volume1hUSD"`
		Volume4HUSD               float64 `json:"volume4hUSD"`
		Volume6HUSD               float64 `json:"volume6hUSD"`
		Volume12HUSD              float64 `json:"volume12hUSD"`
		Volume24HUSD              float64 `json:"volume24hUSD"`
		VolumeBuy1MinUSD          float64 `json:"volumeBuy1minUSD"`
		VolumeBuy5MinUSD          float64 `json:"volumeBuy5minUSD"`
		VolumeBuy15MinUSD         float64 `json:"volumeBuy15minUSD"`
		VolumeBuy1HUSD            float64 `json:"volumeBuy1hUSD"`
		VolumeBuy4HUSD            float64 `json:"volumeBuy4hUSD"`
		VolumeBuy6HUSD            float64 `json:"volumeBuy6hUSD"`
		VolumeBuy12HUSD           float64 `json:"volumeBuy12hUSD"`
		VolumeBuy24HUSD           float64 `json:"volumeBuy24hUSD"`
		VolumeSell1MinUSD         float64 `json:"volumeSell1minUSD"`
		VolumeSell5MinUSD         float64 `json:"volumeSell5minUSD"`
		VolumeSell15MinUSD        float64 `json:"volumeSell15minUSD"`
		VolumeSell1HUSD           float64 `json:"volumeSell1hUSD"`
		VolumeSell4HUSD           float64 `json:"volumeSell4hUSD"`
		VolumeSell6HUSD           float64 `json:"volumeSell6hUSD"`
		VolumeSell12HUSD          float64 `json:"volumeSell12hUSD"`
		VolumeSell24HUSD          float64 `json:"volumeSell24hUSD"`
		Trades1Min                int     `json:"trades1min"`
		Trades5Min                int     `json:"trades5min"`
		Trades15Min               int     `json:"trades15min"`
		Trades1H                  int     `json:"trades1h"`
		Trades4H                  int     `json:"trades4h"`
		Trades6H                  int     `json:"trades6h"`
		Trades12H                 int     `json:"trades12h"`
		Trades24H                 int     `json:"trades24h"`
		Buys1Min                  int     `json:"buys1min"`
		Buys5Min                  int     `json:"buys5min"`
		Buys15Min                 int     `json:"buys15min"`
		Buys1H                    int     `json:"buys1h"`
		Buys4H                    int     `json:"buys4h"`
		Buys6H                    int     `json:"buys6h"`
		Buys12H                   int     `json:"buys12h"`
		Buys24H                   int     `json:"buys24h"`
		Sells1Min                 int     `json:"sells1min"`
		Sells5Min                 int     `json:"sells5min"`
		Sells15Min                int     `json:"sells15min"`
		Sells1H                   int     `json:"sells1h"`
		Sells4H                   int     `json:"sells4h"`
		Sells6H                   int     `json:"sells6h"`
		Sells12H                  int     `json:"sells12h"`
		Sells24H                  int     `json:"sells24h"`
		Buyers1Min                int     `json:"buyers1min"`
		Buyers5Min                int     `json:"buyers5min"`
		Buyers15Min               int     `json:"buyers15min"`
		Buyers1H                  int     `json:"buyers1h"`
		Buyers4H                  int     `json:"buyers4h"`
		Buyers6H                  int     `json:"buyers6h"`
		Buyers12H                 int     `json:"buyers12h"`
		Buyers24H                 int     `json:"buyers24h"`
		Sellers1Min               int     `json:"sellers1min"`
		Sellers5Min               int     `json:"sellers5min"`
		Sellers15Min              int     `json:"sellers15min"`
		Sellers1H                 int     `json:"sellers1h"`
		Sellers4H                 int     `json:"sellers4h"`
		Sellers6H                 int     `json:"sellers6h"`
		Sellers12H                int     `json:"sellers12h"`
		Sellers24H                int     `json:"sellers24h"`
		Traders1Min               int     `json:"traders1min"`
		Traders5Min               int     `json:"traders5min"`
		Traders15Min              int     `json:"traders15min"`
		Traders1H                 int     `json:"traders1h"`
		Traders4H                 int     `json:"traders4h"`
		Traders6H                 int     `json:"traders6h"`
		Traders12H                int     `json:"traders12h"`
		Traders24H                int     `json:"traders24h"`
		FeesPaid1MinUSD           float64 `json:"feesPaid1minUSD"`
		FeesPaid5MinUSD           float64 `json:"feesPaid5minUSD"`
		FeesPaid15MinUSD          float64 `json:"feesPaid15minUSD"`
		FeesPaid1HUSD             float64 `json:"feesPaid1hUSD"`
		FeesPaid4HUSD             float64 `json:"feesPaid4hUSD"`
		FeesPaid6HUSD             float64 `json:"feesPaid6hUSD"`
		FeesPaid12HUSD            float64 `json:"feesPaid12hUSD"`
		FeesPaid24HUSD            float64 `json:"feesPaid24hUSD"`
		TotalFeesPaidUSD          float64 `json:"totalFeesPaidUSD"`
		TotalFeesPaidNativeRaw    string  `json:"totalFeesPaidNativeRaw"`
		OrganicTrades1Min         int     `json:"organicTrades1min"`
		OrganicTrades5Min         int     `json:"organicTrades5min"`
		OrganicTrades15Min        int     `json:"organicTrades15min"`
		OrganicTrades1H           int     `json:"organicTrades1h"`
		OrganicTrades4H           int     `json:"organicTrades4h"`
		OrganicTrades6H           int     `json:"organicTrades6h"`
		OrganicTrades12H          int     `json:"organicTrades12h"`
		OrganicTrades24H          int     `json:"organicTrades24h"`
		OrganicTraders1Min        int     `json:"organicTraders1min"`
		OrganicTraders5Min        int     `json:"organicTraders5min"`
		OrganicTraders15Min       int     `json:"organicTraders15min"`
		OrganicTraders1H          int     `json:"organicTraders1h"`
		OrganicTraders4H          int     `json:"organicTraders4h"`
		OrganicTraders6H          int     `json:"organicTraders6h"`
		OrganicTraders12H         int     `json:"organicTraders12h"`
		OrganicTraders24H         int     `json:"organicTraders24h"`
		OrganicVolume1MinUSD      float64 `json:"organicVolume1minUSD"`
		OrganicVolume5MinUSD      float64 `json:"organicVolume5minUSD"`
		OrganicVolume15MinUSD     float64 `json:"organicVolume15minUSD"`
		OrganicVolume1HUSD        float64 `json:"organicVolume1hUSD"`
		OrganicVolume4HUSD        float64 `json:"organicVolume4hUSD"`
		OrganicVolume6HUSD        float64 `json:"organicVolume6hUSD"`
		OrganicVolume12HUSD       float64 `json:"organicVolume12hUSD"`
		OrganicVolume24HUSD       float64 `json:"organicVolume24hUSD"`
		OrganicVolumeBuy1MinUSD   float64 `json:"organicVolumeBuy1minUSD"`
		OrganicVolumeBuy5MinUSD   float64 `json:"organicVolumeBuy5minUSD"`
		OrganicVolumeBuy15MinUSD  float64 `json:"organicVolumeBuy15minUSD"`
		OrganicVolumeBuy1HUSD     float64 `json:"organicVolumeBuy1hUSD"`
		OrganicVolumeBuy4HUSD     float64 `json:"organicVolumeBuy4hUSD"`
		OrganicVolumeBuy6HUSD     float64 `json:"organicVolumeBuy6hUSD"`
		OrganicVolumeBuy12HUSD    float64 `json:"organicVolumeBuy12hUSD"`
		OrganicVolumeBuy24HUSD    float64 `json:"organicVolumeBuy24hUSD"`
		OrganicVolumeSell1MinUSD  float64 `json:"organicVolumeSell1minUSD"`
		OrganicVolumeSell5MinUSD  float64 `json:"organicVolumeSell5minUSD"`
		OrganicVolumeSell15MinUSD float64 `json:"organicVolumeSell15minUSD"`
		OrganicVolumeSell1HUSD    float64 `json:"organicVolumeSell1hUSD"`
		OrganicVolumeSell4HUSD    float64 `json:"organicVolumeSell4hUSD"`
		OrganicVolumeSell6HUSD    float64 `json:"organicVolumeSell6hUSD"`
		OrganicVolumeSell12HUSD   float64 `json:"organicVolumeSell12hUSD"`
		OrganicVolumeSell24HUSD   float64 `json:"organicVolumeSell24hUSD"`
		OrganicBuys1Min           int     `json:"organicBuys1min"`
		OrganicBuys5Min           int     `json:"organicBuys5min"`
		OrganicBuys15Min          int     `json:"organicBuys15min"`
		OrganicBuys1H             int     `json:"organicBuys1h"`
		OrganicBuys4H             int     `json:"organicBuys4h"`
		OrganicBuys6H             int     `json:"organicBuys6h"`
		OrganicBuys12H            int     `json:"organicBuys12h"`
		OrganicBuys24H            int     `json:"organicBuys24h"`
		OrganicSells1Min          int     `json:"organicSells1min"`
		OrganicSells5Min          int     `json:"organicSells5min"`
		OrganicSells15Min         int     `json:"organicSells15min"`
		OrganicSells1H            int     `json:"organicSells1h"`
		OrganicSells4H            int     `json:"organicSells4h"`
		OrganicSells6H            int     `json:"organicSells6h"`
		OrganicSells12H           int     `json:"organicSells12h"`
		OrganicSells24H           int     `json:"organicSells24h"`
		OrganicBuyers1Min         int     `json:"organicBuyers1min"`
		OrganicBuyers5Min         int     `json:"organicBuyers5min"`
		OrganicBuyers15Min        int     `json:"organicBuyers15min"`
		OrganicBuyers1H           int     `json:"organicBuyers1h"`
		OrganicBuyers4H           int     `json:"organicBuyers4h"`
		OrganicBuyers6H           int     `json:"organicBuyers6h"`
		OrganicBuyers12H          int     `json:"organicBuyers12h"`
		OrganicBuyers24H          int     `json:"organicBuyers24h"`
		OrganicSellers1Min        int     `json:"organicSellers1min"`
		OrganicSellers5Min        int     `json:"organicSellers5min"`
		OrganicSellers15Min       int     `json:"organicSellers15min"`
		OrganicSellers1H          int     `json:"organicSellers1h"`
		OrganicSellers4H          int     `json:"organicSellers4h"`
		OrganicSellers6H          int     `json:"organicSellers6h"`
		OrganicSellers12H         int     `json:"organicSellers12h"`
		OrganicSellers24H         int     `json:"organicSellers24h"`
		CreatedAt                 any     `json:"createdAt"`
		LatestTradeDate           any     `json:"latestTradeDate"`
		HoldersCount              int     `json:"holdersCount"`
		Description               any     `json:"description"`
		Socials                   struct {
			Twitter  any `json:"twitter"`
			Website  any `json:"website"`
			Telegram any `json:"telegram"`
			Others   any `json:"others"`
		} `json:"socials"`
		Security                       any     `json:"security"`
		TwitterReusesCount             int     `json:"twitterReusesCount"`
		TwitterRenameCount             int     `json:"twitterRenameCount"`
		TwitterRenameHistory           []any   `json:"twitterRenameHistory"`
		DeployerMigrationsCount        int     `json:"deployerMigrationsCount"`
		DeployerTokensCount            int     `json:"deployerTokensCount"`
		DexscreenerListed              bool    `json:"dexscreenerListed"`
		DexscreenerHeader              any     `json:"dexscreenerHeader"`
		DexscreenerAdPaid              bool    `json:"dexscreenerAdPaid"`
		DexscreenerAdPaidDate          any     `json:"dexscreenerAdPaidDate"`
		DexscreenerSocialPaid          bool    `json:"dexscreenerSocialPaid"`
		DexscreenerSocialPaidDate      any     `json:"dexscreenerSocialPaidDate"`
		LiveStatus                     any     `json:"liveStatus"`
		LiveThumbnail                  any     `json:"liveThumbnail"`
		LivestreamTitle                any     `json:"livestreamTitle"`
		LiveReplyCount                 any     `json:"liveReplyCount"`
		DexscreenerBoosted             bool    `json:"dexscreenerBoosted"`
		DexscreenerBoostedDate         any     `json:"dexscreenerBoostedDate"`
		DexscreenerBoostedAmount       float64 `json:"dexscreenerBoostedAmount"`
		TrendingScore1Min              float64 `json:"trendingScore1min"`
		TrendingScore5Min              float64 `json:"trendingScore5min"`
		TrendingScore15Min             float64 `json:"trendingScore15min"`
		TrendingScore1H                float64 `json:"trendingScore1h"`
		TrendingScore4H                float64 `json:"trendingScore4h"`
		TrendingScore6H                float64 `json:"trendingScore6h"`
		TrendingScore12H               float64 `json:"trendingScore12h"`
		TrendingScore24H               float64 `json:"trendingScore24h"`
		Top10HoldingsPercentage        float64 `json:"top10HoldingsPercentage"`
		Top50HoldingsPercentage        float64 `json:"top50HoldingsPercentage"`
		Top100HoldingsPercentage       float64 `json:"top100HoldingsPercentage"`
		Top200HoldingsPercentage       float64 `json:"top200HoldingsPercentage"`
		DevHoldingsPercentage          float64 `json:"devHoldingsPercentage"`
		InsidersHoldingsPercentage     float64 `json:"insidersHoldingsPercentage"`
		BundlersHoldingsPercentage     float64 `json:"bundlersHoldingsPercentage"`
		SnipersHoldingsPercentage      float64 `json:"snipersHoldingsPercentage"`
		ProTradersHoldingsPercentage   float64 `json:"proTradersHoldingsPercentage"`
		FreshTradersHoldingsPercentage float64 `json:"freshTradersHoldingsPercentage"`
		InsidersCount                  int     `json:"insidersCount"`
		BundlersCount                  int     `json:"bundlersCount"`
		SnipersCount                   int     `json:"snipersCount"`
		FreshTradersCount              int     `json:"freshTradersCount"`
		ProTradersCount                int     `json:"proTradersCount"`
		FreshTradersBuys               int     `json:"freshTradersBuys"`
		ProTradersBuys                 int     `json:"proTradersBuys"`
		SmartTradersBuys               int     `json:"smartTradersBuys"`
	} `json:"data"`
}

// ========================
// Asset Details API Types
// ========================

type AssetDetailsRequest struct {
	ID          *int   `json:"id,omitempty"`          // Asset ID (optional)
	Address     string `json:"address,omitempty"`     // Token contract address (required if no id)
	Blockchain  string `json:"blockchain,omitempty"`  // Blockchain identifier (required if using address)
	TokensLimit int    `json:"tokensLimit,omitempty"` // Max number of tokens to return (optional, default: 10, max: 50)
}
type AssetDetailsResponse struct {
	Data struct {
		Asset struct {
			ID                  int       `json:"id"`
			Name                string    `json:"name"`
			Symbol              string    `json:"symbol"`
			Logo                string    `json:"logo"`
			Description         string    `json:"description"`
			Rank                int       `json:"rank"`
			NativeChainID       any       `json:"nativeChainId"`
			PriceUSD            float64   `json:"priceUSD"`
			TotalSupply         int       `json:"totalSupply"`
			CirculatingSupply   int       `json:"circulatingSupply"`
			MarketCapUSD        float64   `json:"marketCapUSD"`
			MarketCapDilutedUSD float64   `json:"marketCapDilutedUSD"`
			AthPriceDate        time.Time `json:"athPriceDate"`
			AthPriceUSD         float64   `json:"athPriceUSD"`
			AtlPriceDate        time.Time `json:"atlPriceDate"`
			AtlPriceUSD         float64   `json:"atlPriceUSD"`
			IsStablecoin        bool      `json:"isStablecoin"`
			CreatedAt           time.Time `json:"createdAt"`
			ListedAt            time.Time `json:"listedAt"`
			Socials             struct {
				Audit   any    `json:"audit"`
				Github  string `json:"github"`
				Twitter string `json:"twitter"`
				Website string `json:"website"`
				Kyc     any    `json:"kyc"`
				Chat    string `json:"chat"`
				Discord any    `json:"discord"`
			} `json:"socials"`
		} `json:"asset"`
		Tokens []struct {
			Address                    string  `json:"address"`
			ChainID                    string  `json:"chainId"`
			Symbol                     string  `json:"symbol"`
			Name                       string  `json:"name"`
			Decimals                   int     `json:"decimals"`
			ID                         int     `json:"id"`
			PriceUSD                   float64 `json:"priceUSD"`
			PriceToken                 float64 `json:"priceToken"`
			PriceTokenString           string  `json:"priceTokenString"`
			ApproximateReserveUSD      float64 `json:"approximateReserveUSD"`
			ApproximateReserveTokenRaw string  `json:"approximateReserveTokenRaw"`
			ApproximateReserveToken    float64 `json:"approximateReserveToken"`
			TotalSupply                int     `json:"totalSupply"`
			CirculatingSupply          int     `json:"circulatingSupply"`
			MarketCapUSD               float64 `json:"marketCapUSD"`
			MarketCapDilutedUSD        float64 `json:"marketCapDilutedUSD"`
			Logo                       string  `json:"logo"`
			Rank                       int     `json:"rank"`
			Cexs                       []any   `json:"cexs"`
			Exchange                   struct {
				Name string `json:"name"`
				Logo string `json:"logo"`
			} `json:"exchange"`
			Factory                   string    `json:"factory"`
			Source                    string    `json:"source"`
			LiquidityUSD              float64   `json:"liquidityUSD"`
			LiquidityMaxUSD           float64   `json:"liquidityMaxUSD"`
			Bonded                    bool      `json:"bonded"`
			BondingPercentage         int       `json:"bondingPercentage"`
			PoolAddress               string    `json:"poolAddress"`
			Blockchain                string    `json:"blockchain"`
			Type                      string    `json:"type"`
			TokenType                 string    `json:"tokenType"`
			Deployer                  string    `json:"deployer"`
			BondedAt                  time.Time `json:"bondedAt"`
			AthUSD                    float64   `json:"athUSD"`
			AtlUSD                    float64   `json:"atlUSD"`
			AthDate                   time.Time `json:"athDate"`
			AtlDate                   time.Time `json:"atlDate"`
			PriceChange1MinPercentage float64   `json:"priceChange1minPercentage"`
			PriceChange5MinPercentage float64   `json:"priceChange5minPercentage"`
			PriceChange1HPercentage   float64   `json:"priceChange1hPercentage"`
			PriceChange4HPercentage   float64   `json:"priceChange4hPercentage"`
			PriceChange6HPercentage   float64   `json:"priceChange6hPercentage"`
			PriceChange12HPercentage  float64   `json:"priceChange12hPercentage"`
			PriceChange24HPercentage  float64   `json:"priceChange24hPercentage"`
			Volume1MinUSD             float64   `json:"volume1minUSD"`
			Volume5MinUSD             float64   `json:"volume5minUSD"`
			Volume15MinUSD            float64   `json:"volume15minUSD"`
			Volume1HUSD               float64   `json:"volume1hUSD"`
			Volume4HUSD               float64   `json:"volume4hUSD"`
			Volume6HUSD               float64   `json:"volume6hUSD"`
			Volume12HUSD              float64   `json:"volume12hUSD"`
			Volume24HUSD              float64   `json:"volume24hUSD"`
			VolumeBuy1MinUSD          float64   `json:"volumeBuy1minUSD"`
			VolumeBuy5MinUSD          float64   `json:"volumeBuy5minUSD"`
			VolumeBuy15MinUSD         float64   `json:"volumeBuy15minUSD"`
			VolumeBuy1HUSD            float64   `json:"volumeBuy1hUSD"`
			VolumeBuy4HUSD            float64   `json:"volumeBuy4hUSD"`
			VolumeBuy6HUSD            float64   `json:"volumeBuy6hUSD"`
			VolumeBuy12HUSD           float64   `json:"volumeBuy12hUSD"`
			VolumeBuy24HUSD           float64   `json:"volumeBuy24hUSD"`
			VolumeSell1MinUSD         float64   `json:"volumeSell1minUSD"`
			VolumeSell5MinUSD         float64   `json:"volumeSell5minUSD"`
			VolumeSell15MinUSD        float64   `json:"volumeSell15minUSD"`
			VolumeSell1HUSD           float64   `json:"volumeSell1hUSD"`
			VolumeSell4HUSD           float64   `json:"volumeSell4hUSD"`
			VolumeSell6HUSD           float64   `json:"volumeSell6hUSD"`
			VolumeSell12HUSD          float64   `json:"volumeSell12hUSD"`
			VolumeSell24HUSD          float64   `json:"volumeSell24hUSD"`
			Trades1Min                int       `json:"trades1min"`
			Trades5Min                int       `json:"trades5min"`
			Trades15Min               int       `json:"trades15min"`
			Trades1H                  int       `json:"trades1h"`
			Trades4H                  int       `json:"trades4h"`
			Trades6H                  int       `json:"trades6h"`
			Trades12H                 int       `json:"trades12h"`
			Trades24H                 int       `json:"trades24h"`
			Buys1Min                  int       `json:"buys1min"`
			Buys5Min                  int       `json:"buys5min"`
			Buys15Min                 int       `json:"buys15min"`
			Buys1H                    int       `json:"buys1h"`
			Buys4H                    int       `json:"buys4h"`
			Buys6H                    int       `json:"buys6h"`
			Buys12H                   int       `json:"buys12h"`
			Buys24H                   int       `json:"buys24h"`
			Sells1Min                 int       `json:"sells1min"`
			Sells5Min                 int       `json:"sells5min"`
			Sells15Min                int       `json:"sells15min"`
			Sells1H                   int       `json:"sells1h"`
			Sells4H                   int       `json:"sells4h"`
			Sells6H                   int       `json:"sells6h"`
			Sells12H                  int       `json:"sells12h"`
			Sells24H                  int       `json:"sells24h"`
			Buyers1Min                int       `json:"buyers1min"`
			Buyers5Min                int       `json:"buyers5min"`
			Buyers15Min               int       `json:"buyers15min"`
			Buyers1H                  int       `json:"buyers1h"`
			Buyers4H                  int       `json:"buyers4h"`
			Buyers6H                  int       `json:"buyers6h"`
			Buyers12H                 int       `json:"buyers12h"`
			Buyers24H                 int       `json:"buyers24h"`
			Sellers1Min               int       `json:"sellers1min"`
			Sellers5Min               int       `json:"sellers5min"`
			Sellers15Min              int       `json:"sellers15min"`
			Sellers1H                 int       `json:"sellers1h"`
			Sellers4H                 int       `json:"sellers4h"`
			Sellers6H                 int       `json:"sellers6h"`
			Sellers12H                int       `json:"sellers12h"`
			Sellers24H                int       `json:"sellers24h"`
			Traders1Min               int       `json:"traders1min"`
			Traders5Min               int       `json:"traders5min"`
			Traders15Min              int       `json:"traders15min"`
			Traders1H                 int       `json:"traders1h"`
			Traders4H                 int       `json:"traders4h"`
			Traders6H                 int       `json:"traders6h"`
			Traders12H                int       `json:"traders12h"`
			Traders24H                int       `json:"traders24h"`
			FeesPaid1MinUSD           float64   `json:"feesPaid1minUSD"`
			FeesPaid5MinUSD           float64   `json:"feesPaid5minUSD"`
			FeesPaid15MinUSD          float64   `json:"feesPaid15minUSD"`
			FeesPaid1HUSD             float64   `json:"feesPaid1hUSD"`
			FeesPaid4HUSD             float64   `json:"feesPaid4hUSD"`
			FeesPaid6HUSD             float64   `json:"feesPaid6hUSD"`
			FeesPaid12HUSD            float64   `json:"feesPaid12hUSD"`
			FeesPaid24HUSD            float64   `json:"feesPaid24hUSD"`
			TotalFeesPaidUSD          float64   `json:"totalFeesPaidUSD"`
			TotalFeesPaidNativeRaw    string    `json:"totalFeesPaidNativeRaw"`
			OrganicTrades1Min         int       `json:"organicTrades1min"`
			OrganicTrades5Min         int       `json:"organicTrades5min"`
			OrganicTrades15Min        int       `json:"organicTrades15min"`
			OrganicTrades1H           int       `json:"organicTrades1h"`
			OrganicTrades4H           int       `json:"organicTrades4h"`
			OrganicTrades6H           int       `json:"organicTrades6h"`
			OrganicTrades12H          int       `json:"organicTrades12h"`
			OrganicTrades24H          int       `json:"organicTrades24h"`
			OrganicTraders1Min        int       `json:"organicTraders1min"`
			OrganicTraders5Min        int       `json:"organicTraders5min"`
			OrganicTraders15Min       int       `json:"organicTraders15min"`
			OrganicTraders1H          int       `json:"organicTraders1h"`
			OrganicTraders4H          int       `json:"organicTraders4h"`
			OrganicTraders6H          int       `json:"organicTraders6h"`
			OrganicTraders12H         int       `json:"organicTraders12h"`
			OrganicTraders24H         int       `json:"organicTraders24h"`
			OrganicVolume1MinUSD      float64   `json:"organicVolume1minUSD"`
			OrganicVolume5MinUSD      float64   `json:"organicVolume5minUSD"`
			OrganicVolume15MinUSD     float64   `json:"organicVolume15minUSD"`
			OrganicVolume1HUSD        float64   `json:"organicVolume1hUSD"`
			OrganicVolume4HUSD        float64   `json:"organicVolume4hUSD"`
			OrganicVolume6HUSD        float64   `json:"organicVolume6hUSD"`
			OrganicVolume12HUSD       float64   `json:"organicVolume12hUSD"`
			OrganicVolume24HUSD       float64   `json:"organicVolume24hUSD"`
			OrganicVolumeBuy1MinUSD   float64   `json:"organicVolumeBuy1minUSD"`
			OrganicVolumeBuy5MinUSD   float64   `json:"organicVolumeBuy5minUSD"`
			OrganicVolumeBuy15MinUSD  float64   `json:"organicVolumeBuy15minUSD"`
			OrganicVolumeBuy1HUSD     float64   `json:"organicVolumeBuy1hUSD"`
			OrganicVolumeBuy4HUSD     float64   `json:"organicVolumeBuy4hUSD"`
			OrganicVolumeBuy6HUSD     float64   `json:"organicVolumeBuy6hUSD"`
			OrganicVolumeBuy12HUSD    float64   `json:"organicVolumeBuy12hUSD"`
			OrganicVolumeBuy24HUSD    float64   `json:"organicVolumeBuy24hUSD"`
			OrganicVolumeSell1MinUSD  float64   `json:"organicVolumeSell1minUSD"`
			OrganicVolumeSell5MinUSD  float64   `json:"organicVolumeSell5minUSD"`
			OrganicVolumeSell15MinUSD float64   `json:"organicVolumeSell15minUSD"`
			OrganicVolumeSell1HUSD    float64   `json:"organicVolumeSell1hUSD"`
			OrganicVolumeSell4HUSD    float64   `json:"organicVolumeSell4hUSD"`
			OrganicVolumeSell6HUSD    float64   `json:"organicVolumeSell6hUSD"`
			OrganicVolumeSell12HUSD   float64   `json:"organicVolumeSell12hUSD"`
			OrganicVolumeSell24HUSD   float64   `json:"organicVolumeSell24hUSD"`
			OrganicBuys1Min           int       `json:"organicBuys1min"`
			OrganicBuys5Min           int       `json:"organicBuys5min"`
			OrganicBuys15Min          int       `json:"organicBuys15min"`
			OrganicBuys1H             int       `json:"organicBuys1h"`
			OrganicBuys4H             int       `json:"organicBuys4h"`
			OrganicBuys6H             int       `json:"organicBuys6h"`
			OrganicBuys12H            int       `json:"organicBuys12h"`
			OrganicBuys24H            int       `json:"organicBuys24h"`
			OrganicSells1Min          int       `json:"organicSells1min"`
			OrganicSells5Min          int       `json:"organicSells5min"`
			OrganicSells15Min         int       `json:"organicSells15min"`
			OrganicSells1H            int       `json:"organicSells1h"`
			OrganicSells4H            int       `json:"organicSells4h"`
			OrganicSells6H            int       `json:"organicSells6h"`
			OrganicSells12H           int       `json:"organicSells12h"`
			OrganicSells24H           int       `json:"organicSells24h"`
			OrganicBuyers1Min         int       `json:"organicBuyers1min"`
			OrganicBuyers5Min         int       `json:"organicBuyers5min"`
			OrganicBuyers15Min        int       `json:"organicBuyers15min"`
			OrganicBuyers1H           int       `json:"organicBuyers1h"`
			OrganicBuyers4H           int       `json:"organicBuyers4h"`
			OrganicBuyers6H           int       `json:"organicBuyers6h"`
			OrganicBuyers12H          int       `json:"organicBuyers12h"`
			OrganicBuyers24H          int       `json:"organicBuyers24h"`
			OrganicSellers1Min        int       `json:"organicSellers1min"`
			OrganicSellers5Min        int       `json:"organicSellers5min"`
			OrganicSellers15Min       int       `json:"organicSellers15min"`
			OrganicSellers1H          int       `json:"organicSellers1h"`
			OrganicSellers4H          int       `json:"organicSellers4h"`
			OrganicSellers6H          int       `json:"organicSellers6h"`
			OrganicSellers12H         int       `json:"organicSellers12h"`
			OrganicSellers24H         int       `json:"organicSellers24h"`
			CreatedAt                 time.Time `json:"createdAt"`
			LatestTradeDate           time.Time `json:"latestTradeDate"`
			HoldersCount              int       `json:"holdersCount"`
			Description               string    `json:"description"`
			Socials                   struct {
				Twitter  string `json:"twitter"`
				Website  any    `json:"website"`
				Telegram any    `json:"telegram"`
				Others   struct {
				} `json:"others"`
			} `json:"socials"`
			Security struct {
				BuyTax           string `json:"buyTax"`
				SellTax          string `json:"sellTax"`
				TransferPausable bool   `json:"transferPausable"`
				IsBlacklisted    bool   `json:"isBlacklisted"`
				NoMintAuthority  bool   `json:"noMintAuthority"`
				BalanceMutable   bool   `json:"balanceMutable"`
			} `json:"security"`
			TwitterReusesCount             int       `json:"twitterReusesCount"`
			TwitterRenameCount             int       `json:"twitterRenameCount"`
			TwitterRenameHistory           []any     `json:"twitterRenameHistory"`
			DeployerMigrationsCount        int       `json:"deployerMigrationsCount"`
			DeployerTokensCount            int       `json:"deployerTokensCount"`
			DexscreenerListed              bool      `json:"dexscreenerListed"`
			DexscreenerHeader              string    `json:"dexscreenerHeader"`
			DexscreenerAdPaid              bool      `json:"dexscreenerAdPaid"`
			DexscreenerAdPaidDate          any       `json:"dexscreenerAdPaidDate"`
			DexscreenerSocialPaid          bool      `json:"dexscreenerSocialPaid"`
			DexscreenerSocialPaidDate      any       `json:"dexscreenerSocialPaidDate"`
			LiveStatus                     any       `json:"liveStatus"`
			LiveThumbnail                  any       `json:"liveThumbnail"`
			LivestreamTitle                any       `json:"livestreamTitle"`
			LiveReplyCount                 any       `json:"liveReplyCount"`
			DexscreenerBoosted             bool      `json:"dexscreenerBoosted"`
			DexscreenerBoostedDate         time.Time `json:"dexscreenerBoostedDate"`
			DexscreenerBoostedAmount       int       `json:"dexscreenerBoostedAmount"`
			TrendingScore1Min              float64   `json:"trendingScore1min"`
			TrendingScore5Min              float64   `json:"trendingScore5min"`
			TrendingScore15Min             float64   `json:"trendingScore15min"`
			TrendingScore1H                float64   `json:"trendingScore1h"`
			TrendingScore4H                float64   `json:"trendingScore4h"`
			TrendingScore6H                float64   `json:"trendingScore6h"`
			TrendingScore12H               float64   `json:"trendingScore12h"`
			TrendingScore24H               float64   `json:"trendingScore24h"`
			Top10HoldingsPercentage        float64   `json:"top10HoldingsPercentage"`
			Top50HoldingsPercentage        float64   `json:"top50HoldingsPercentage"`
			Top100HoldingsPercentage       float64   `json:"top100HoldingsPercentage"`
			Top200HoldingsPercentage       float64   `json:"top200HoldingsPercentage"`
			DevHoldingsPercentage          int       `json:"devHoldingsPercentage"`
			InsidersHoldingsPercentage     float64   `json:"insidersHoldingsPercentage"`
			BundlersHoldingsPercentage     float64   `json:"bundlersHoldingsPercentage"`
			SnipersHoldingsPercentage      float64   `json:"snipersHoldingsPercentage"`
			ProTradersHoldingsPercentage   int       `json:"proTradersHoldingsPercentage"`
			FreshTradersHoldingsPercentage int       `json:"freshTradersHoldingsPercentage"`
			SmartTradersHoldingsPercentage int       `json:"smartTradersHoldingsPercentage"`
			InsidersCount                  int       `json:"insidersCount"`
			BundlersCount                  int       `json:"bundlersCount"`
			SnipersCount                   int       `json:"snipersCount"`
			FreshTradersCount              int       `json:"freshTradersCount"`
			ProTradersCount                int       `json:"proTradersCount"`
			SmartTradersCount              int       `json:"smartTradersCount"`
			FreshTradersBuys               int       `json:"freshTradersBuys"`
			ProTradersBuys                 int       `json:"proTradersBuys"`
			SmartTradersBuys               int       `json:"smartTradersBuys"`
		} `json:"tokens"`
		TokensCount int `json:"tokensCount"`
	} `json:"data"`
}

// ========================
// Market Details API Types
// ========================

type MarketDetailsRequest struct {
	Address    string `json:"address"`              // Token contract address (required)
	Blockchain string `json:"blockchain,omitempty"` // Blockchain name (optional)
}
type MarketDetailsResponse struct {
	Data struct {
		Base struct {
			Address                        string    `json:"address"`
			ChainID                        string    `json:"chainId"`
			Symbol                         string    `json:"symbol"`
			Name                           string    `json:"name"`
			Decimals                       int       `json:"decimals"`
			ID                             int       `json:"id"`
			PriceUSD                       float64   `json:"priceUSD"`
			PriceToken                     float64   `json:"priceToken"`
			PriceTokenString               string    `json:"priceTokenString"`
			ApproximateReserveUSD          float64   `json:"approximateReserveUSD"`
			ApproximateReserveTokenRaw     string    `json:"approximateReserveTokenRaw"`
			ApproximateReserveToken        float64   `json:"approximateReserveToken"`
			TotalSupply                    float64   `json:"totalSupply"`
			CirculatingSupply              int       `json:"circulatingSupply"`
			MarketCapUSD                   float64   `json:"marketCapUSD"`
			MarketCapDilutedUSD            float64   `json:"marketCapDilutedUSD"`
			Logo                           string    `json:"logo"`
			Factory                        string    `json:"factory"`
			Source                         string    `json:"source"`
			SourceFactory                  string    `json:"sourceFactory"`
			LiquidityUSD                   float64   `json:"liquidityUSD"`
			LiquidityMaxUSD                float64   `json:"liquidityMaxUSD"`
			Bonded                         bool      `json:"bonded"`
			BondingPercentage              int       `json:"bondingPercentage"`
			BondingCurveAddress            string    `json:"bondingCurveAddress"`
			PreBondingFactory              string    `json:"preBondingFactory"`
			Blockchain                     string    `json:"blockchain"`
			Deployer                       string    `json:"deployer"`
			CreatedAt                      time.Time `json:"createdAt"`
			BondedAt                       any       `json:"bondedAt"`
			AthUSD                         float64   `json:"athUSD"`
			AtlUSD                         float64   `json:"atlUSD"`
			AthDate                        time.Time `json:"athDate"`
			AtlDate                        time.Time `json:"atlDate"`
			Top10HoldingsPercentage        float64   `json:"top10HoldingsPercentage"`
			Top50HoldingsPercentage        float64   `json:"top50HoldingsPercentage"`
			Top100HoldingsPercentage       float64   `json:"top100HoldingsPercentage"`
			Top200HoldingsPercentage       float64   `json:"top200HoldingsPercentage"`
			DevHoldingsPercentage          int       `json:"devHoldingsPercentage"`
			InsidersHoldingsPercentage     float64   `json:"insidersHoldingsPercentage"`
			BundlersHoldingsPercentage     float64   `json:"bundlersHoldingsPercentage"`
			SnipersHoldingsPercentage      float64   `json:"snipersHoldingsPercentage"`
			ProTradersHoldingsPercentage   int       `json:"proTradersHoldingsPercentage"`
			FreshTradersHoldingsPercentage int       `json:"freshTradersHoldingsPercentage"`
			InsidersCount                  int       `json:"insidersCount"`
			BundlersCount                  int       `json:"bundlersCount"`
			SnipersCount                   int       `json:"snipersCount"`
			FreshTradersCount              int       `json:"freshTradersCount"`
			ProTradersCount                int       `json:"proTradersCount"`
		} `json:"base"`
		Quote struct {
			Address                        string    `json:"address"`
			ChainID                        string    `json:"chainId"`
			Symbol                         string    `json:"symbol"`
			Name                           string    `json:"name"`
			Decimals                       int       `json:"decimals"`
			ID                             int       `json:"id"`
			PriceUSD                       float64   `json:"priceUSD"`
			PriceToken                     float64   `json:"priceToken"`
			PriceTokenString               string    `json:"priceTokenString"`
			ApproximateReserveUSD          float64   `json:"approximateReserveUSD"`
			ApproximateReserveTokenRaw     string    `json:"approximateReserveTokenRaw"`
			ApproximateReserveToken        float64   `json:"approximateReserveToken"`
			TotalSupply                    int       `json:"totalSupply"`
			CirculatingSupply              int       `json:"circulatingSupply"`
			MarketCapUSD                   float64   `json:"marketCapUSD"`
			MarketCapDilutedUSD            float64   `json:"marketCapDilutedUSD"`
			Logo                           string    `json:"logo"`
			Factory                        string    `json:"factory"`
			Source                         string    `json:"source"`
			SourceFactory                  string    `json:"sourceFactory"`
			LiquidityUSD                   float64   `json:"liquidityUSD"`
			LiquidityMaxUSD                float64   `json:"liquidityMaxUSD"`
			Bonded                         bool      `json:"bonded"`
			BondingPercentage              int       `json:"bondingPercentage"`
			BondingCurveAddress            string    `json:"bondingCurveAddress"`
			PreBondingFactory              string    `json:"preBondingFactory"`
			Blockchain                     string    `json:"blockchain"`
			Deployer                       string    `json:"deployer"`
			CreatedAt                      time.Time `json:"createdAt"`
			BondedAt                       any       `json:"bondedAt"`
			AthUSD                         float64   `json:"athUSD"`
			AtlUSD                         float64   `json:"atlUSD"`
			AthDate                        time.Time `json:"athDate"`
			AtlDate                        time.Time `json:"atlDate"`
			Top10HoldingsPercentage        int       `json:"top10HoldingsPercentage"`
			Top50HoldingsPercentage        int       `json:"top50HoldingsPercentage"`
			Top100HoldingsPercentage       int       `json:"top100HoldingsPercentage"`
			Top200HoldingsPercentage       int       `json:"top200HoldingsPercentage"`
			DevHoldingsPercentage          int       `json:"devHoldingsPercentage"`
			InsidersHoldingsPercentage     int       `json:"insidersHoldingsPercentage"`
			BundlersHoldingsPercentage     int       `json:"bundlersHoldingsPercentage"`
			SnipersHoldingsPercentage      int       `json:"snipersHoldingsPercentage"`
			ProTradersHoldingsPercentage   int       `json:"proTradersHoldingsPercentage"`
			FreshTradersHoldingsPercentage int       `json:"freshTradersHoldingsPercentage"`
			InsidersCount                  int       `json:"insidersCount"`
			BundlersCount                  int       `json:"bundlersCount"`
			SnipersCount                   int       `json:"snipersCount"`
			FreshTradersCount              int       `json:"freshTradersCount"`
			ProTradersCount                int       `json:"proTradersCount"`
		} `json:"quote"`
		LiquidityUSD    float64   `json:"liquidityUSD"`
		LatestTradeDate time.Time `json:"latestTradeDate"`
		Blockchain      string    `json:"blockchain"`
		Address         string    `json:"address"`
		CreatedAt       time.Time `json:"createdAt"`
		Type            string    `json:"type"`
		Exchange        struct {
			Name string `json:"name"`
			Logo string `json:"logo"`
		} `json:"exchange"`
		Factory                   string  `json:"factory"`
		PriceUSD                  float64 `json:"priceUSD"`
		PriceToken                float64 `json:"priceToken"`
		PriceTokenString          string  `json:"priceTokenString"`
		BaseToken                 string  `json:"baseToken"`
		QuoteToken                string  `json:"quoteToken"`
		Bonded                    bool    `json:"bonded"`
		BondingPercentage         int     `json:"bondingPercentage"`
		PreBondingPoolAddress     string  `json:"preBondingPoolAddress"`
		SourceFactory             any     `json:"sourceFactory"`
		TotalFeesPaidUSD          float64 `json:"totalFeesPaidUSD"`
		TotalFeesPaidNativeRaw    string  `json:"totalFeesPaidNativeRaw"`
		PriceChange1MinPercentage float64 `json:"priceChange1minPercentage"`
		PriceChange5MinPercentage float64 `json:"priceChange5minPercentage"`
		PriceChange1HPercentage   float64 `json:"priceChange1hPercentage"`
		PriceChange4HPercentage   float64 `json:"priceChange4hPercentage"`
		PriceChange6HPercentage   float64 `json:"priceChange6hPercentage"`
		PriceChange12HPercentage  float64 `json:"priceChange12hPercentage"`
		PriceChange24HPercentage  float64 `json:"priceChange24hPercentage"`
		Volume1MinUSD             float64 `json:"volume1minUSD"`
		Volume5MinUSD             float64 `json:"volume5minUSD"`
		Volume15MinUSD            float64 `json:"volume15minUSD"`
		Volume1HUSD               float64 `json:"volume1hUSD"`
		Volume4HUSD               float64 `json:"volume4hUSD"`
		Volume6HUSD               float64 `json:"volume6hUSD"`
		Volume12HUSD              float64 `json:"volume12hUSD"`
		Volume24HUSD              float64 `json:"volume24hUSD"`
		VolumeBuy1MinUSD          float64 `json:"volumeBuy1minUSD"`
		VolumeBuy5MinUSD          float64 `json:"volumeBuy5minUSD"`
		VolumeBuy15MinUSD         float64 `json:"volumeBuy15minUSD"`
		VolumeBuy1HUSD            float64 `json:"volumeBuy1hUSD"`
		VolumeBuy4HUSD            float64 `json:"volumeBuy4hUSD"`
		VolumeBuy6HUSD            float64 `json:"volumeBuy6hUSD"`
		VolumeBuy12HUSD           float64 `json:"volumeBuy12hUSD"`
		VolumeBuy24HUSD           float64 `json:"volumeBuy24hUSD"`
		VolumeSell1MinUSD         float64 `json:"volumeSell1minUSD"`
		VolumeSell5MinUSD         float64 `json:"volumeSell5minUSD"`
		VolumeSell15MinUSD        float64 `json:"volumeSell15minUSD"`
		VolumeSell1HUSD           float64 `json:"volumeSell1hUSD"`
		VolumeSell4HUSD           float64 `json:"volumeSell4hUSD"`
		VolumeSell6HUSD           float64 `json:"volumeSell6hUSD"`
		VolumeSell12HUSD          float64 `json:"volumeSell12hUSD"`
		VolumeSell24HUSD          float64 `json:"volumeSell24hUSD"`
		Trades1Min                int     `json:"trades1min"`
		Trades5Min                int     `json:"trades5min"`
		Trades15Min               int     `json:"trades15min"`
		Trades1H                  int     `json:"trades1h"`
		Trades4H                  int     `json:"trades4h"`
		Trades6H                  int     `json:"trades6h"`
		Trades12H                 int     `json:"trades12h"`
		Trades24H                 int     `json:"trades24h"`
		Buys1Min                  int     `json:"buys1min"`
		Buys5Min                  int     `json:"buys5min"`
		Buys15Min                 int     `json:"buys15min"`
		Buys1H                    int     `json:"buys1h"`
		Buys4H                    int     `json:"buys4h"`
		Buys6H                    int     `json:"buys6h"`
		Buys12H                   int     `json:"buys12h"`
		Buys24H                   int     `json:"buys24h"`
		Sells1Min                 int     `json:"sells1min"`
		Sells5Min                 int     `json:"sells5min"`
		Sells15Min                int     `json:"sells15min"`
		Sells1H                   int     `json:"sells1h"`
		Sells4H                   int     `json:"sells4h"`
		Sells6H                   int     `json:"sells6h"`
		Sells12H                  int     `json:"sells12h"`
		Sells24H                  int     `json:"sells24h"`
		Buyers1Min                int     `json:"buyers1min"`
		Buyers5Min                int     `json:"buyers5min"`
		Buyers15Min               int     `json:"buyers15min"`
		Buyers1H                  int     `json:"buyers1h"`
		Buyers4H                  int     `json:"buyers4h"`
		Buyers6H                  int     `json:"buyers6h"`
		Buyers12H                 int     `json:"buyers12h"`
		Buyers24H                 int     `json:"buyers24h"`
		Sellers1Min               int     `json:"sellers1min"`
		Sellers5Min               int     `json:"sellers5min"`
		Sellers15Min              int     `json:"sellers15min"`
		Sellers1H                 int     `json:"sellers1h"`
		Sellers4H                 int     `json:"sellers4h"`
		Sellers6H                 int     `json:"sellers6h"`
		Sellers12H                int     `json:"sellers12h"`
		Sellers24H                int     `json:"sellers24h"`
		Traders1Min               int     `json:"traders1min"`
		Traders5Min               int     `json:"traders5min"`
		Traders15Min              int     `json:"traders15min"`
		Traders1H                 int     `json:"traders1h"`
		Traders4H                 int     `json:"traders4h"`
		Traders6H                 int     `json:"traders6h"`
		Traders12H                int     `json:"traders12h"`
		Traders24H                int     `json:"traders24h"`
		FeesPaid1MinUSD           int     `json:"feesPaid1minUSD"`
		FeesPaid5MinUSD           float64 `json:"feesPaid5minUSD"`
		FeesPaid15MinUSD          float64 `json:"feesPaid15minUSD"`
		FeesPaid1HUSD             float64 `json:"feesPaid1hUSD"`
		FeesPaid4HUSD             float64 `json:"feesPaid4hUSD"`
		FeesPaid6HUSD             float64 `json:"feesPaid6hUSD"`
		FeesPaid12HUSD            float64 `json:"feesPaid12hUSD"`
		FeesPaid24HUSD            float64 `json:"feesPaid24hUSD"`
		HoldersCount              int     `json:"holdersCount"`
		Source                    any     `json:"source"`
		Deployer                  any     `json:"deployer"`
		TokenSymbol               string  `json:"tokenSymbol"`
		TokenName                 string  `json:"tokenName"`
		DexscreenerListed         bool    `json:"dexscreenerListed"`
		DeployerMigrations        int     `json:"deployerMigrations"`
		Socials                   struct {
			Twitter  any `json:"twitter"`
			Website  any `json:"website"`
			Telegram any `json:"telegram"`
			Others   struct {
			} `json:"others"`
		} `json:"socials"`
		Description any `json:"description"`
		Security    struct {
			BuyTax           string `json:"buyTax"`
			SellTax          string `json:"sellTax"`
			TransferPausable bool   `json:"transferPausable"`
			Top10Holders     string `json:"top10Holders"`
			IsBlacklisted    bool   `json:"isBlacklisted"`
			NoMintAuthority  bool   `json:"noMintAuthority"`
			BalanceMutable   bool   `json:"balanceMutable"`
			BurnRate         string `json:"burnRate"`
		} `json:"security"`
		TwitterReusesCount   int   `json:"twitterReusesCount"`
		TwitterRenameCount   int   `json:"twitterRenameCount"`
		TwitterRenameHistory []any `json:"twitterRenameHistory"`
		ExtraData            struct {
			Account0         string `json:"account0"`
			Account1         string `json:"account1"`
			OpenOrders       string `json:"openOrders"`
			TargetOrders     string `json:"targetOrders"`
			MarketProgramID  string `json:"marketProgramId"`
			MarketBids       string `json:"marketBids"`
			MarketAsks       string `json:"marketAsks"`
			MarketEventQueue string `json:"marketEventQueue"`
			MarketBaseVault  string `json:"marketBaseVault"`
			MarketQuoteVault string `json:"marketQuoteVault"`
			VaultSignerNonce string `json:"vaultSignerNonce"`
		} `json:"extraData"`
		Top10HoldingsPercentage        float64 `json:"top10HoldingsPercentage"`
		Top50HoldingsPercentage        float64 `json:"top50HoldingsPercentage"`
		Top100HoldingsPercentage       float64 `json:"top100HoldingsPercentage"`
		Top200HoldingsPercentage       float64 `json:"top200HoldingsPercentage"`
		DevHoldingsPercentage          int     `json:"devHoldingsPercentage"`
		InsidersHoldingsPercentage     float64 `json:"insidersHoldingsPercentage"`
		BundlersHoldingsPercentage     float64 `json:"bundlersHoldingsPercentage"`
		SnipersHoldingsPercentage      float64 `json:"snipersHoldingsPercentage"`
		ProTradersHoldingsPercentage   int     `json:"proTradersHoldingsPercentage"`
		FreshTradersHoldingsPercentage int     `json:"freshTradersHoldingsPercentage"`
		InsidersCount                  int     `json:"insidersCount"`
		BundlersCount                  int     `json:"bundlersCount"`
		SnipersCount                   int     `json:"snipersCount"`
		FreshTradersCount              int     `json:"freshTradersCount"`
		ProTradersCount                int     `json:"proTradersCount"`
	} `json:"data"`
}

// ========================
// Token Markets API Types
// ========================

type TokenMarketsRequest struct {
	Address    string `json:"address"`              // Asset name, symbol, or contract address (required)
	Blockchain string `json:"blockchain,omitempty"` // Blockchain identifier (optional)
	Limit      string `json:"limit,omitempty"`      // Blockchain identifier (optional)
}

type TokenMarketsResponse struct {
	Data []struct {
		Base struct {
			Address                        string    `json:"address"`
			ChainID                        string    `json:"chainId"`
			Symbol                         string    `json:"symbol"`
			Name                           string    `json:"name"`
			Decimals                       int       `json:"decimals"`
			ID                             int       `json:"id"`
			PriceUSD                       float64   `json:"priceUSD"`
			PriceToken                     float64   `json:"priceToken"`
			PriceTokenString               string    `json:"priceTokenString"`
			ApproximateReserveUSD          float64   `json:"approximateReserveUSD"`
			ApproximateReserveTokenRaw     string    `json:"approximateReserveTokenRaw"`
			ApproximateReserveToken        float64   `json:"approximateReserveToken"`
			TotalSupply                    float64   `json:"totalSupply"`
			CirculatingSupply              float64   `json:"circulatingSupply"`
			MarketCapUSD                   float64   `json:"marketCapUSD"`
			MarketCapDilutedUSD            float64   `json:"marketCapDilutedUSD"`
			Logo                           string    `json:"logo"`
			Factory                        string    `json:"factory"`
			Source                         string    `json:"source"`
			SourceFactory                  string    `json:"sourceFactory"`
			LiquidityUSD                   float64   `json:"liquidityUSD"`
			LiquidityMaxUSD                float64   `json:"liquidityMaxUSD"`
			Bonded                         bool      `json:"bonded"`
			BondingPercentage              int       `json:"bondingPercentage"`
			BondingCurveAddress            string    `json:"bondingCurveAddress"`
			PreBondingFactory              string    `json:"preBondingFactory"`
			Blockchain                     string    `json:"blockchain"`
			Deployer                       string    `json:"deployer"`
			CreatedAt                      time.Time `json:"createdAt"`
			BondedAt                       any       `json:"bondedAt"`
			AthUSD                         float64   `json:"athUSD"`
			AtlUSD                         float64   `json:"atlUSD"`
			AthDate                        time.Time `json:"athDate"`
			AtlDate                        time.Time `json:"atlDate"`
			Top10HoldingsPercentage        float64   `json:"top10HoldingsPercentage"`
			Top50HoldingsPercentage        int       `json:"top50HoldingsPercentage"`
			Top100HoldingsPercentage       int       `json:"top100HoldingsPercentage"`
			Top200HoldingsPercentage       int       `json:"top200HoldingsPercentage"`
			DevHoldingsPercentage          int       `json:"devHoldingsPercentage"`
			InsidersHoldingsPercentage     int       `json:"insidersHoldingsPercentage"`
			BundlersHoldingsPercentage     int       `json:"bundlersHoldingsPercentage"`
			SnipersHoldingsPercentage      float64   `json:"snipersHoldingsPercentage"`
			ProTradersHoldingsPercentage   int       `json:"proTradersHoldingsPercentage"`
			FreshTradersHoldingsPercentage int       `json:"freshTradersHoldingsPercentage"`
			InsidersCount                  int       `json:"insidersCount"`
			BundlersCount                  int       `json:"bundlersCount"`
			SnipersCount                   int       `json:"snipersCount"`
			FreshTradersCount              int       `json:"freshTradersCount"`
			ProTradersCount                int       `json:"proTradersCount"`
		} `json:"base"`
		Quote struct {
			Address                        string    `json:"address"`
			ChainID                        string    `json:"chainId"`
			Symbol                         string    `json:"symbol"`
			Name                           string    `json:"name"`
			Decimals                       int       `json:"decimals"`
			ID                             int       `json:"id"`
			PriceUSD                       float64   `json:"priceUSD"`
			PriceToken                     float64   `json:"priceToken"`
			PriceTokenString               string    `json:"priceTokenString"`
			ApproximateReserveUSD          float64   `json:"approximateReserveUSD"`
			ApproximateReserveTokenRaw     string    `json:"approximateReserveTokenRaw"`
			ApproximateReserveToken        float64   `json:"approximateReserveToken"`
			TotalSupply                    float64   `json:"totalSupply"`
			CirculatingSupply              float64   `json:"circulatingSupply"`
			MarketCapUSD                   float64   `json:"marketCapUSD"`
			MarketCapDilutedUSD            float64   `json:"marketCapDilutedUSD"`
			Logo                           string    `json:"logo"`
			Factory                        string    `json:"factory"`
			Source                         string    `json:"source"`
			SourceFactory                  string    `json:"sourceFactory"`
			LiquidityUSD                   float64   `json:"liquidityUSD"`
			LiquidityMaxUSD                float64   `json:"liquidityMaxUSD"`
			Bonded                         bool      `json:"bonded"`
			BondingPercentage              int       `json:"bondingPercentage"`
			BondingCurveAddress            string    `json:"bondingCurveAddress"`
			PreBondingFactory              string    `json:"preBondingFactory"`
			Blockchain                     string    `json:"blockchain"`
			Deployer                       string    `json:"deployer"`
			CreatedAt                      time.Time `json:"createdAt"`
			BondedAt                       any       `json:"bondedAt"`
			AthUSD                         float64   `json:"athUSD"`
			AtlUSD                         float64   `json:"atlUSD"`
			AthDate                        time.Time `json:"athDate"`
			AtlDate                        time.Time `json:"atlDate"`
			Top10HoldingsPercentage        float64   `json:"top10HoldingsPercentage"`
			Top50HoldingsPercentage        float64   `json:"top50HoldingsPercentage"`
			Top100HoldingsPercentage       float64   `json:"top100HoldingsPercentage"`
			Top200HoldingsPercentage       float64   `json:"top200HoldingsPercentage"`
			DevHoldingsPercentage          int       `json:"devHoldingsPercentage"`
			InsidersHoldingsPercentage     float64   `json:"insidersHoldingsPercentage"`
			BundlersHoldingsPercentage     float64   `json:"bundlersHoldingsPercentage"`
			SnipersHoldingsPercentage      float64   `json:"snipersHoldingsPercentage"`
			ProTradersHoldingsPercentage   int       `json:"proTradersHoldingsPercentage"`
			FreshTradersHoldingsPercentage int       `json:"freshTradersHoldingsPercentage"`
			InsidersCount                  int       `json:"insidersCount"`
			BundlersCount                  int       `json:"bundlersCount"`
			SnipersCount                   int       `json:"snipersCount"`
			FreshTradersCount              int       `json:"freshTradersCount"`
			ProTradersCount                int       `json:"proTradersCount"`
		} `json:"quote"`
		LiquidityUSD    float64   `json:"liquidityUSD"`
		LatestTradeDate time.Time `json:"latestTradeDate"`
		Blockchain      string    `json:"blockchain"`
		Address         string    `json:"address"`
		CreatedAt       time.Time `json:"createdAt"`
		Type            string    `json:"type"`
		Exchange        struct {
			Name string `json:"name"`
			Logo string `json:"logo"`
		} `json:"exchange"`
		Factory                   string  `json:"factory"`
		PriceUSD                  float64 `json:"priceUSD"`
		PriceToken                float64 `json:"priceToken"`
		PriceTokenString          string  `json:"priceTokenString"`
		BaseToken                 string  `json:"baseToken"`
		QuoteToken                string  `json:"quoteToken"`
		Bonded                    bool    `json:"bonded"`
		BondingPercentage         int     `json:"bondingPercentage"`
		PreBondingPoolAddress     string  `json:"preBondingPoolAddress"`
		SourceFactory             any     `json:"sourceFactory"`
		TotalFeesPaidUSD          float64 `json:"totalFeesPaidUSD"`
		TotalFeesPaidNativeRaw    string  `json:"totalFeesPaidNativeRaw"`
		PriceChange1MinPercentage float64 `json:"priceChange1minPercentage"`
		PriceChange5MinPercentage float64 `json:"priceChange5minPercentage"`
		PriceChange1HPercentage   float64 `json:"priceChange1hPercentage"`
		PriceChange4HPercentage   float64 `json:"priceChange4hPercentage"`
		PriceChange6HPercentage   float64 `json:"priceChange6hPercentage"`
		PriceChange12HPercentage  float64 `json:"priceChange12hPercentage"`
		PriceChange24HPercentage  float64 `json:"priceChange24hPercentage"`
		Volume1MinUSD             float64 `json:"volume1minUSD"`
		Volume5MinUSD             float64 `json:"volume5minUSD"`
		Volume15MinUSD            float64 `json:"volume15minUSD"`
		Volume1HUSD               float64 `json:"volume1hUSD"`
		Volume4HUSD               float64 `json:"volume4hUSD"`
		Volume6HUSD               float64 `json:"volume6hUSD"`
		Volume12HUSD              float64 `json:"volume12hUSD"`
		Volume24HUSD              float64 `json:"volume24hUSD"`
		VolumeBuy1MinUSD          float64 `json:"volumeBuy1minUSD"`
		VolumeBuy5MinUSD          float64 `json:"volumeBuy5minUSD"`
		VolumeBuy15MinUSD         float64 `json:"volumeBuy15minUSD"`
		VolumeBuy1HUSD            float64 `json:"volumeBuy1hUSD"`
		VolumeBuy4HUSD            float64 `json:"volumeBuy4hUSD"`
		VolumeBuy6HUSD            float64 `json:"volumeBuy6hUSD"`
		VolumeBuy12HUSD           float64 `json:"volumeBuy12hUSD"`
		VolumeBuy24HUSD           float64 `json:"volumeBuy24hUSD"`
		VolumeSell1MinUSD         float64 `json:"volumeSell1minUSD"`
		VolumeSell5MinUSD         float64 `json:"volumeSell5minUSD"`
		VolumeSell15MinUSD        float64 `json:"volumeSell15minUSD"`
		VolumeSell1HUSD           float64 `json:"volumeSell1hUSD"`
		VolumeSell4HUSD           float64 `json:"volumeSell4hUSD"`
		VolumeSell6HUSD           float64 `json:"volumeSell6hUSD"`
		VolumeSell12HUSD          float64 `json:"volumeSell12hUSD"`
		VolumeSell24HUSD          float64 `json:"volumeSell24hUSD"`
		Trades1Min                int     `json:"trades1min"`
		Trades5Min                int     `json:"trades5min"`
		Trades15Min               int     `json:"trades15min"`
		Trades1H                  int     `json:"trades1h"`
		Trades4H                  int     `json:"trades4h"`
		Trades6H                  int     `json:"trades6h"`
		Trades12H                 int     `json:"trades12h"`
		Trades24H                 int     `json:"trades24h"`
		Buys1Min                  int     `json:"buys1min"`
		Buys5Min                  int     `json:"buys5min"`
		Buys15Min                 int     `json:"buys15min"`
		Buys1H                    int     `json:"buys1h"`
		Buys4H                    int     `json:"buys4h"`
		Buys6H                    int     `json:"buys6h"`
		Buys12H                   int     `json:"buys12h"`
		Buys24H                   int     `json:"buys24h"`
		Sells1Min                 int     `json:"sells1min"`
		Sells5Min                 int     `json:"sells5min"`
		Sells15Min                int     `json:"sells15min"`
		Sells1H                   int     `json:"sells1h"`
		Sells4H                   int     `json:"sells4h"`
		Sells6H                   int     `json:"sells6h"`
		Sells12H                  int     `json:"sells12h"`
		Sells24H                  int     `json:"sells24h"`
		Buyers1Min                int     `json:"buyers1min"`
		Buyers5Min                int     `json:"buyers5min"`
		Buyers15Min               int     `json:"buyers15min"`
		Buyers1H                  int     `json:"buyers1h"`
		Buyers4H                  int     `json:"buyers4h"`
		Buyers6H                  int     `json:"buyers6h"`
		Buyers12H                 int     `json:"buyers12h"`
		Buyers24H                 int     `json:"buyers24h"`
		Sellers1Min               int     `json:"sellers1min"`
		Sellers5Min               int     `json:"sellers5min"`
		Sellers15Min              int     `json:"sellers15min"`
		Sellers1H                 int     `json:"sellers1h"`
		Sellers4H                 int     `json:"sellers4h"`
		Sellers6H                 int     `json:"sellers6h"`
		Sellers12H                int     `json:"sellers12h"`
		Sellers24H                int     `json:"sellers24h"`
		Traders1Min               int     `json:"traders1min"`
		Traders5Min               int     `json:"traders5min"`
		Traders15Min              int     `json:"traders15min"`
		Traders1H                 int     `json:"traders1h"`
		Traders4H                 int     `json:"traders4h"`
		Traders6H                 int     `json:"traders6h"`
		Traders12H                int     `json:"traders12h"`
		Traders24H                int     `json:"traders24h"`
		FeesPaid1MinUSD           float64 `json:"feesPaid1minUSD"`
		FeesPaid5MinUSD           float64 `json:"feesPaid5minUSD"`
		FeesPaid15MinUSD          float64 `json:"feesPaid15minUSD"`
		FeesPaid1HUSD             float64 `json:"feesPaid1hUSD"`
		FeesPaid4HUSD             float64 `json:"feesPaid4hUSD"`
		FeesPaid6HUSD             float64 `json:"feesPaid6hUSD"`
		FeesPaid12HUSD            float64 `json:"feesPaid12hUSD"`
		FeesPaid24HUSD            float64 `json:"feesPaid24hUSD"`
		HoldersCount              int     `json:"holdersCount"`
		Source                    any     `json:"source"`
		Deployer                  string  `json:"deployer"`
		TokenSymbol               string  `json:"tokenSymbol"`
		TokenName                 string  `json:"tokenName"`
		DexscreenerListed         bool    `json:"dexscreenerListed"`
		DeployerMigrations        int     `json:"deployerMigrations"`
		Socials                   struct {
			Twitter  any `json:"twitter"`
			Website  any `json:"website"`
			Telegram any `json:"telegram"`
			Others   struct {
			} `json:"others"`
		} `json:"socials"`
		Description any `json:"description"`
		Security    struct {
			BuyTax           string `json:"buyTax"`
			SellTax          string `json:"sellTax"`
			TransferPausable bool   `json:"transferPausable"`
			Top10Holders     string `json:"top10Holders"`
			IsBlacklisted    bool   `json:"isBlacklisted"`
			BalanceMutable   bool   `json:"balanceMutable"`
			BurnRate         string `json:"burnRate"`
			IsHoneypot       bool   `json:"isHoneypot"`
			IsNotOpenSource  bool   `json:"isNotOpenSource"`
			Renounced        bool   `json:"renounced"`
			Locked           string `json:"locked"`
			IsWhitelisted    bool   `json:"isWhitelisted"`
			IsMintable       bool   `json:"isMintable"`
			ModifyableTax    bool   `json:"modifyableTax"`
			SelfDestruct     bool   `json:"selfDestruct"`
		} `json:"security"`
		TwitterReusesCount   int   `json:"twitterReusesCount"`
		TwitterRenameCount   int   `json:"twitterRenameCount"`
		TwitterRenameHistory []any `json:"twitterRenameHistory"`
		ExtraData            struct {
			SqrtPriceX96 string `json:"sqrtPriceX96"`
			TickSpacing  int    `json:"tickSpacing"`
			PoolKey      struct {
				Currency0   string `json:"currency0"`
				Currency1   string `json:"currency1"`
				Fee         int    `json:"fee"`
				TickSpacing int    `json:"tickSpacing"`
				Hooks       string `json:"hooks"`
			} `json:"poolKey"`
		} `json:"extraData,omitempty"`
		Top10HoldingsPercentage        float64 `json:"top10HoldingsPercentage"`
		Top50HoldingsPercentage        int     `json:"top50HoldingsPercentage"`
		Top100HoldingsPercentage       int     `json:"top100HoldingsPercentage"`
		Top200HoldingsPercentage       int     `json:"top200HoldingsPercentage"`
		DevHoldingsPercentage          int     `json:"devHoldingsPercentage"`
		InsidersHoldingsPercentage     int     `json:"insidersHoldingsPercentage"`
		BundlersHoldingsPercentage     int     `json:"bundlersHoldingsPercentage"`
		SnipersHoldingsPercentage      float64 `json:"snipersHoldingsPercentage"`
		ProTradersHoldingsPercentage   int     `json:"proTradersHoldingsPercentage"`
		FreshTradersHoldingsPercentage int     `json:"freshTradersHoldingsPercentage"`
		InsidersCount                  int     `json:"insidersCount"`
		BundlersCount                  int     `json:"bundlersCount"`
		SnipersCount                   int     `json:"snipersCount"`
		FreshTradersCount              int     `json:"freshTradersCount"`
		ProTradersCount                int     `json:"proTradersCount"`
		ExtraData0                     struct {
			SqrtPriceX96 string `json:"sqrtPriceX96"`
			SqrtPriceX64 string `json:"sqrtPriceX64"`
			TickSpacing  int    `json:"tickSpacing"`
			Tick         int    `json:"tick"`
		} `json:"extraData,omitempty"`
	} `json:"data"`
}
